version: "3.3"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
        ENV_GITHUB_CLIENT_ID: 
        ENV_GITHUB_CLIENT_SECRET: 
        ENV_GOOGLE_CLIENT_ID: 
        ENV_GOOGLE_CLIENT_SECRET:
  database:
    image: "mariadb:10.8.3"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyPass
    volumes:
      - type: bind
        source: /home/sopheap/Downloads/database
        target: /var/lib/mysql
    ports:
       - "3306:3306"
volumes:
  database:
