server:
  port: 8080
spring:
  application:
    name: kh-note
  datasource:
    password: MyPass
    #    url: jdbc:postgresql://localhost:5432/note
    url: jdbc:mariadb://database:3306/khnote?user=app_user&password=MyPass
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
        format_sql: true
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${ENV_GITHUB_CLIENT_ID}
            client-secret: ${ENV_GITHUB_CLIENT_SECRET}
          google:
            client-id: ${ENV_GOOGLE_CLIENT_ID}
            client-secret: ${ENV_GOOGLE_CLIENT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
logging:
  level:
    org.springframework.security: DEBUG
